---
title: 'Project 1: Wrangling, Exploration, Visualization'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

## Data Wrangling, Exploration, Visualization

### Nitya Kodali nk9723

### Introduction 

The datasets that I used are cousin_marriage and drinks. I thought that the drinks dataset was interesting and wanted to find something that had a countries variable to join the two datasets. The cousin_marriage dataset is about a taboo topic so I wanted to see if there was a correlation between alcohol and cousin marriage. I also really liked the articles that were written about the datasets, by Mona Chalabi. I found the datasets and articles tied to them through the fivethirtyeight package.
The cousin marriage dataset had only two variables, the country and the percent of marriages that are cosanguineous. The drinks dataset had five variables, the country, the servings of beer, sprits, and wine per person, and the total litres of pure alcohol per person (per year). I doubt that there will be any significant associations between drinking and cousin marriage, but I am curious to see if there is one. If there is an association to cousin marriage, I believe it will not matter the type of alcohol (beer/spirit/wine) but just the total liters.

```{R}
library(fivethirtyeight)
data1 <- drinks
data2 <- cousin_marriage
```

### Tidying: Reshaping

Since my datasets were already tidy, I showed that I can use pivot_longer and pivot_wider with the drinks dataset (data1). I used the columns related to beer, wine, and spirit servings to pivot my dataset longer and assigned this long dataset to "untidy". Then, I pivoted the untidy dataset wider to convert the dataset back to it's original tidy form (retidied).

```{R}
library(tidyverse)
data1 %>% pivot_longer(2:4, names_to="serving_type", values_to="count") -> untidy
head(untidy)
untidy %>% pivot_wider(names_from="serving_type", values_from="count") -> data1
head(data1)
```

    
### Joining/Merging

```{R}
data1 %>% summarize(n())
data2 %>% summarize(n())
data1 %>% summarize(n_distinct(country))
data2 %>% summarize(n_distinct(country))
data1 %>% anti_join(data2, by="country")
data2 %>% anti_join(data1, by="country")
data2 %>% mutate(country=str_replace(country, "United States", "USA")) %>% mutate(country=str_replace(country, "The Netherlands", "Netherlands")) %>% mutate(country=str_replace(country, "Great Britain", "United Kingdom")) -> data2
data1 %>% inner_join(data2, by="country")
data1 %>% inner_join(data2, by="country") -> joined_data
```

On their own, the datasets each have 193 rows and 70 rows. For both of these datasets, the countries in the observations are all distinct. Therefore, there are 193 unique countries in the drinks dataset (data1) and 70 unique countries in the cousin_marriage dataset (data2). The drinks dataset (data1) has 126 countires that do not have a match in the cousin_marriage dataset (data2). The cousin_marriage dataset (data2) has 3 countries that the drinks dataset (data1) does not have. This was seen through an antijoin. However, upon closer inspection, these three countries did not have a match due to naming differences. This was promptly fixed using the dplyr function mutate. The two datasets have 70 countries in common, which can be seen with an innerjoin.
It made no difference on whether or not I used a leftjoin with data1 onto data2 or an inner join on my datasets to join them, since data2 did not have any countries that were not in data1. In order to do this, I piped the first dataset (drinks) to an inner join function, which inner joined drinks to cousin_marriages (data1 to data2). I called this merged dataset joined_data. Joined_data has 70 observations with 6 variables while data1 (drinks) had more observations (193) with less variables (5) and data2 had the same number of observations (70) with less variables (2).
This means that the 126 countries that were in data1 (drinks) that were not in data2 (cousin_marriages) were dropped. The problem with this is a loss of good data.

###  Wrangling

```{R}
library(stringr)
joined_data %>% mutate("percentclass"= case_when(percent > 5 ~ 'Greater than 5 percent', TRUE ~ 'Less than 5 percent')) -> joined_data
joined_data %>% mutate("servings.total" = wine_servings+beer_servings+spirit_servings)
str_detect(joined_data$percentclass, paste("G.", collapse = '|'))
joined_data %>% filter(total_litres_of_pure_alcohol >= 5) %>% dplyr::select(-percent) %>% arrange(desc(beer_servings))
joined_data %>% group_by(percentclass) %>% summarize(n())
```

Here, I used mutate to create a categorical variable as I didn't have any. I also use the function case_when inside of mutate. I then used mutate to demonstrate creating a new variable that is the function of other variables. I also used stringr with regex to detect all observations with greater than 5 percent for their percentclass variable. I also explored my data using all six dplyr functions.

```{R}
library(gt)
MedAbsDev <- function(x) median(abs(x-median(x)))
joined_data %>% summarize(mean=mean(beer_servings), sd=sd(beer_servings), min=min(beer_servings), max=max(beer_servings), MedAbsDev=MedAbsDev(beer_servings))
joined_data %>% summarize(mean=mean(spirit_servings), sd=sd(spirit_servings), min=min(spirit_servings), max=max(spirit_servings), MedAbsDev=MedAbsDev(spirit_servings))
joined_data %>% summarize(mean=mean(wine_servings), sd=sd(wine_servings), min=min(wine_servings), max=max(wine_servings), MedAbsDev=MedAbsDev(wine_servings))
joined_data %>% summarize(mean=mean(total_litres_of_pure_alcohol), sd=sd(total_litres_of_pure_alcohol), min=min(total_litres_of_pure_alcohol), max=max(total_litres_of_pure_alcohol), MedAbsDev=MedAbsDev(total_litres_of_pure_alcohol))
joined_data %>% group_by(percentclass) %>% summarize(n=n()) %>% gt %>% tab_header(title=md("**Categorical Variable**"))
joined_data %>% summarize_all(function(x)sum(is.na(x)))
```

Here, I computed summary statistics for all my numeric variables, using unique functions inside of summarize. One of the functions(MedAbsDev) was defined by me and then used. I also checked my categorical variable counts for each level. This count was portrayed using the package gt.

```{R}
joined_data %>% group_by(percentclass) %>% summarize(mean=mean(beer_servings), sd=sd(beer_servings), min=min(beer_servings), max=max(beer_servings), MedAbsDev=MedAbsDev(beer_servings))
joined_data %>% group_by(percentclass) %>% summarize(mean=mean(spirit_servings), sd=sd(spirit_servings), min=min(spirit_servings), max=max(spirit_servings), MedAbsDev=MedAbsDev(spirit_servings))
joined_data %>% group_by(percentclass) %>% summarize(mean=mean(wine_servings), sd=sd(wine_servings), min=min(wine_servings), max=max(wine_servings), MedAbsDev=MedAbsDev(wine_servings))
joined_data %>% group_by(percentclass) %>% summarize(mean=mean(total_litres_of_pure_alcohol), sd=sd(total_litres_of_pure_alcohol), min=min(total_litres_of_pure_alcohol), max=max(total_litres_of_pure_alcohol), MedAbsDev=MedAbsDev(total_litres_of_pure_alcohol))
```

I then grouped by the categorical variable and reran my summary statistics. 

Overall, my results showed that there was indeed a correlation between the total pure alcohol in liters per person per year and the rate of cousin marriage in the country. This difference in averages across the percentclass definitely carried throughout the various types of servings (beer, spirit, wine).

### Visualizing

```{R}
joined_data %>% ggplot(aes(x = total_litres_of_pure_alcohol, y= percent, color=percentclass)) + geom_point() + geom_smooth(method = lm) + theme_dark() + scale_y_continuous(breaks = seq(0,75,10), name="Percent Cousin Marriage") + scale_x_continuous(breaks = seq(0,15,3), name="Total Litres of Pure Alcohol") + theme(legend.title.align = 0.5) + labs(col="Legend") + ggtitle("Cousin Marriage and Alcohol Consumption")
```

In my first plot I compared the percent of people in marriages that were cousin marriages with the total liters of pure alcohol directly. This showed a very clear relationship with there being a slight upward trend in the total liters of pure alcohol for higher percents of cousin marriage. However, for those countries with less than 5 percent of marriages being cousin marriages, the total liters of pure alcohol didn't seem to really have a relationship with it. This is also the plot in which I added more tick marks on the y axis to better visualize the data.

```{R}
joined_data %>% ggplot(aes(x=percentclass)) + geom_bar(aes(y=total_litres_of_pure_alcohol), stat = "summary", fun=mean, width=.7) + geom_errorbar(aes(y=total_litres_of_pure_alcohol), stat = "summary", fun.data=mean_se, width=.4) + theme_light() + labs(x="Percent Cousin Marriage") + scale_y_continuous(breaks = seq(0,10,2), name="Total Litres of Pure Alcohol") + ggtitle("Cousin Marriage vs Total Alcohol Consumption")
```

Then, I made the same comparison of the countries with less than or greater than 5 percent of their marriages being consanguineous with the total liters of pure alcohol, but in bar chart form. This showed that there was a much higher total alcohol consumed for countries with less than 5 percent when compared with those that have greater than 5 percent.

```{R}
colors <- c("Beer" = "red", "Wine"= "blue", "Spirit"= "purple")
joined_data %>% ggplot(aes(x=percent)) + geom_point(aes(y=beer_servings, color="Beer"), stat="summary", fun=mean, size=1.5) + geom_point(aes(y=spirit_servings, color="Spirit"), stat="summary", fun=mean) + geom_point(aes(y=wine_servings, color="Wine"), stat="summary", fun=mean) + geom_smooth(method="lm", aes(y=beer_servings, color="Beer")) + geom_smooth(method="lm", aes(y=spirit_servings, color="Spirit")) + geom_smooth(method="lm", aes(y=wine_servings, color="Wine")) + labs(x="Percent Cousin Marriage", col="Legend") + scale_y_continuous(breaks = seq(-150,350,50), limits = c(-150,350), name="Servings") + ggtitle("Cousin Marriage vs Type of Serving") + theme_gray()
```

In my third plot, I wanted to see if there was a relationship between the type of serving and the incidence of cousin marriage. There didn't seem to be a big difference in the impact of type of serving across the three types.

### Concluding Remarks

Overall this project helped me understand R much better, and it really felt like I was putting all the skills I have learned so far in this class into one project.




